# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"


Vagrant.configure("2") do |config|

    config.vm.define "dz5" do |dz5|
        dz5.vm.box = "yan4ik/centos-7-oldkernel"
        dz5.vm.hostname = "dz5"
    end

end

